### ISSUE TITLE
Separate shortcuts for faster alignment

### ISSUE THREAD

**Issue by getflourish** [webpatch/Handy-Tools#1]
I really like your approach of showing a simple but helpful UI. I use very similar actions already. I can imagine to have a command for "equal vertical spacing" that would show the dialog with the "vertical" setting selected already. Then I would not need to use the mouse to make a selection. :)

Great inspiration!

**Comment by webpatch** [comment]
Yes, use shortcuts is  much faster than use UI. I agree with that. But  shortcuts is hard to remember.
So, i  build a simple UI and use local settings to remember the last direction that you selected to simplify the whole process.

If who want to use those function with shortcuts separately, i thinks  [this plugin](https://github.com/bomberstudios/sketch-commands/tree/master/Align) is more appropriate.

BTW, thank you to help me find out the bug that the remember setting doesn't work.
