### ISSUE TITLE
Please add this to the plugin directory

### ISSUE THREAD

**Issue by ricburton** [webpatch/Handy-Tools#2]
This is great! It belongs in the directory.

**Comment by webpatch** [comment]
That's pretty easy!  
1. open the "Plugins" menu and select "Reveal Plugins Folder..."<br>
<img width="122" alt="step" src="https://cloud.githubusercontent.com/assets/1796834/9188982/61fb0afc-4015-11e5-9386-c065d1ac2f69.png">
2. create a folder (any name) under the "Plugins" directory
3. drag the file ("Align To....sketchplugin","Spacing....sketchplugin") and the "Hidden & UnHidden" folder to the folder that you created!
4. done!
