### ISSUE TITLE
Doesn't work properly with object on different levels

### ISSUE THREAD

**Issue by rubiroid** [webpatch/Handy-Tools#3]
If objects are on the same level in layer list it works great. But when one object is in subfolder it doesn't work properly.

**Comment by rohapa** [comment]
It doesn't work at all with Sketch 3.42

**Comment by webpatch** [comment]
@rohapa  Try the new release file.

**Comment by webpatch** [comment]
@rubiroid  Thaks for report.

**Comment by webpatch** [comment]
@rubiroid Problem solved. Use the latest version.

**Comment by rubiroid** [comment]
Thanx a lot!
